### ISSUE TITLE
trigger set labels are all 0s

### ISSUE THREAD

**Issue by aveni** [adiyoss/WatermarkNN#1]
If you print out the trigger set labels during watermark training, the labels are all 0, not randomized (0-9). 

To recreate, add the line ```print (wmtargets)``` before the main loop in `def train(...):` under trainer.py. If you then run `python train.py --wmtrain`  you'll see a list of tensors with 0 values.

I think this has to do with how the wmloader labels are trying to be set in `helpers/loaders.py` ? It might be easier to just use the default folder structure assumed by `datasets.ImageFolder()`.

**Comment by adiyoss** [comment]
Hi @aveni, you are absolutely right, sorry for that. I already did what you suggested but for some reason, it slipped away...:( 
I fixed the code, it should be fine now.
